# Generated by Django 4.2.7 on 2023-11-17 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='tipo_usuario',
            field=models.CharField(choices=[('paciente', 'Paciente'), ('administrador', 'Administrador'), ('medico', 'Medico'), ('secretaria', 'Secretaria')], max_length=50, verbose_name='Tipo de usuario'),
        ),
    ]
