# Generated by Django 4.2.1 on 2023-11-17 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_perfil_tipo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='tipo_usuario',
            field=models.CharField(choices=[('paciente', 'Paciente'), ('medico', 'Médico'), ('Secretaria', 'Secretaria'), ('administrador', 'Administrador'), ('Superusuario', 'Superusuario')], max_length=50, verbose_name='Tipo de usuario'),
        ),
    ]
